/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as MovilRouteRouteImport } from './routes/_movil/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSeguimientoRouteImport } from './routes/_authenticated/seguimiento'
import { Route as AuthenticatedInasistentesRouteImport } from './routes/_authenticated/inasistentes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrearActaRouteImport } from './routes/_authenticated/crear-acta'
import { Route as AuthenticatedActasRouteImport } from './routes/_authenticated/actas'
import { Route as MovilMovilQrRouteImport } from './routes/_movil/movil.qr'
import { Route as MovilMovilCalendarioRouteImport } from './routes/_movil/movil.calendario'
import { Route as MovilMovilAsistenciaRouteImport } from './routes/_movil/movil.asistencia'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const MovilRouteRoute = MovilRouteRouteImport.update({
  id: '/_movil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeguimientoRoute =
  AuthenticatedSeguimientoRouteImport.update({
    id: '/seguimiento',
    path: '/seguimiento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInasistentesRoute =
  AuthenticatedInasistentesRouteImport.update({
    id: '/inasistentes',
    path: '/inasistentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrearActaRoute = AuthenticatedCrearActaRouteImport.update({
  id: '/crear-acta',
  path: '/crear-acta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActasRoute = AuthenticatedActasRouteImport.update({
  id: '/actas',
  path: '/actas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MovilMovilQrRoute = MovilMovilQrRouteImport.update({
  id: '/movil/qr',
  path: '/movil/qr',
  getParentRoute: () => MovilRouteRoute,
} as any)
const MovilMovilCalendarioRoute = MovilMovilCalendarioRouteImport.update({
  id: '/movil/calendario',
  path: '/movil/calendario',
  getParentRoute: () => MovilRouteRoute,
} as any)
const MovilMovilAsistenciaRoute = MovilMovilAsistenciaRouteImport.update({
  id: '/movil/asistencia',
  path: '/movil/asistencia',
  getParentRoute: () => MovilRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/actas': typeof AuthenticatedActasRoute
  '/crear-acta': typeof AuthenticatedCrearActaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inasistentes': typeof AuthenticatedInasistentesRoute
  '/seguimiento': typeof AuthenticatedSeguimientoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/movil/asistencia': typeof MovilMovilAsistenciaRoute
  '/movil/calendario': typeof MovilMovilCalendarioRoute
  '/movil/qr': typeof MovilMovilQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/actas': typeof AuthenticatedActasRoute
  '/crear-acta': typeof AuthenticatedCrearActaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inasistentes': typeof AuthenticatedInasistentesRoute
  '/seguimiento': typeof AuthenticatedSeguimientoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/movil/asistencia': typeof MovilMovilAsistenciaRoute
  '/movil/calendario': typeof MovilMovilCalendarioRoute
  '/movil/qr': typeof MovilMovilQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_movil': typeof MovilRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/_authenticated/actas': typeof AuthenticatedActasRoute
  '/_authenticated/crear-acta': typeof AuthenticatedCrearActaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inasistentes': typeof AuthenticatedInasistentesRoute
  '/_authenticated/seguimiento': typeof AuthenticatedSeguimientoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_movil/movil/asistencia': typeof MovilMovilAsistenciaRoute
  '/_movil/movil/calendario': typeof MovilMovilCalendarioRoute
  '/_movil/movil/qr': typeof MovilMovilQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/actas'
    | '/crear-acta'
    | '/dashboard'
    | '/inasistentes'
    | '/seguimiento'
    | '/usuarios'
    | '/movil/asistencia'
    | '/movil/calendario'
    | '/movil/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/actas'
    | '/crear-acta'
    | '/dashboard'
    | '/inasistentes'
    | '/seguimiento'
    | '/usuarios'
    | '/movil/asistencia'
    | '/movil/calendario'
    | '/movil/qr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_movil'
    | '/demo'
    | '/login'
    | '/_authenticated/actas'
    | '/_authenticated/crear-acta'
    | '/_authenticated/dashboard'
    | '/_authenticated/inasistentes'
    | '/_authenticated/seguimiento'
    | '/_authenticated/usuarios'
    | '/_movil/movil/asistencia'
    | '/_movil/movil/calendario'
    | '/_movil/movil/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MovilRouteRoute: typeof MovilRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_movil': {
      id: '/_movil'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MovilRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seguimiento': {
      id: '/_authenticated/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof AuthenticatedSeguimientoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inasistentes': {
      id: '/_authenticated/inasistentes'
      path: '/inasistentes'
      fullPath: '/inasistentes'
      preLoaderRoute: typeof AuthenticatedInasistentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crear-acta': {
      id: '/_authenticated/crear-acta'
      path: '/crear-acta'
      fullPath: '/crear-acta'
      preLoaderRoute: typeof AuthenticatedCrearActaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actas': {
      id: '/_authenticated/actas'
      path: '/actas'
      fullPath: '/actas'
      preLoaderRoute: typeof AuthenticatedActasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_movil/movil/qr': {
      id: '/_movil/movil/qr'
      path: '/movil/qr'
      fullPath: '/movil/qr'
      preLoaderRoute: typeof MovilMovilQrRouteImport
      parentRoute: typeof MovilRouteRoute
    }
    '/_movil/movil/calendario': {
      id: '/_movil/movil/calendario'
      path: '/movil/calendario'
      fullPath: '/movil/calendario'
      preLoaderRoute: typeof MovilMovilCalendarioRouteImport
      parentRoute: typeof MovilRouteRoute
    }
    '/_movil/movil/asistencia': {
      id: '/_movil/movil/asistencia'
      path: '/movil/asistencia'
      fullPath: '/movil/asistencia'
      preLoaderRoute: typeof MovilMovilAsistenciaRouteImport
      parentRoute: typeof MovilRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActasRoute: typeof AuthenticatedActasRoute
  AuthenticatedCrearActaRoute: typeof AuthenticatedCrearActaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInasistentesRoute: typeof AuthenticatedInasistentesRoute
  AuthenticatedSeguimientoRoute: typeof AuthenticatedSeguimientoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActasRoute: AuthenticatedActasRoute,
  AuthenticatedCrearActaRoute: AuthenticatedCrearActaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInasistentesRoute: AuthenticatedInasistentesRoute,
  AuthenticatedSeguimientoRoute: AuthenticatedSeguimientoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MovilRouteRouteChildren {
  MovilMovilAsistenciaRoute: typeof MovilMovilAsistenciaRoute
  MovilMovilCalendarioRoute: typeof MovilMovilCalendarioRoute
  MovilMovilQrRoute: typeof MovilMovilQrRoute
}

const MovilRouteRouteChildren: MovilRouteRouteChildren = {
  MovilMovilAsistenciaRoute: MovilMovilAsistenciaRoute,
  MovilMovilCalendarioRoute: MovilMovilCalendarioRoute,
  MovilMovilQrRoute: MovilMovilQrRoute,
}

const MovilRouteRouteWithChildren = MovilRouteRoute._addFileChildren(
  MovilRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MovilRouteRoute: MovilRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
