/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSeguimientoRouteImport } from './routes/_authenticated/seguimiento'
import { Route as AuthenticatedInasistentesRouteImport } from './routes/_authenticated/inasistentes'
import { Route as AuthenticatedEvidenciasRouteImport } from './routes/_authenticated/evidencias'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrearActaRouteImport } from './routes/_authenticated/crear-acta'
import { Route as AuthenticatedActasRouteImport } from './routes/_authenticated/actas'
import { Route as AuthenticatedMovilSemaforoRouteImport } from './routes/_authenticated/movil.semaforo'
import { Route as AuthenticatedMovilQrRouteImport } from './routes/_authenticated/movil.qr'
import { Route as AuthenticatedMovilCalendarioRouteImport } from './routes/_authenticated/movil.calendario'
import { Route as AuthenticatedMovilAsistenciaRouteImport } from './routes/_authenticated/movil.asistencia'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeguimientoRoute =
  AuthenticatedSeguimientoRouteImport.update({
    id: '/seguimiento',
    path: '/seguimiento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInasistentesRoute =
  AuthenticatedInasistentesRouteImport.update({
    id: '/inasistentes',
    path: '/inasistentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvidenciasRoute = AuthenticatedEvidenciasRouteImport.update({
  id: '/evidencias',
  path: '/evidencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrearActaRoute = AuthenticatedCrearActaRouteImport.update({
  id: '/crear-acta',
  path: '/crear-acta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActasRoute = AuthenticatedActasRouteImport.update({
  id: '/actas',
  path: '/actas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovilSemaforoRoute =
  AuthenticatedMovilSemaforoRouteImport.update({
    id: '/movil/semaforo',
    path: '/movil/semaforo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovilQrRoute = AuthenticatedMovilQrRouteImport.update({
  id: '/movil/qr',
  path: '/movil/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovilCalendarioRoute =
  AuthenticatedMovilCalendarioRouteImport.update({
    id: '/movil/calendario',
    path: '/movil/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovilAsistenciaRoute =
  AuthenticatedMovilAsistenciaRouteImport.update({
    id: '/movil/asistencia',
    path: '/movil/asistencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/actas': typeof AuthenticatedActasRoute
  '/crear-acta': typeof AuthenticatedCrearActaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evidencias': typeof AuthenticatedEvidenciasRoute
  '/inasistentes': typeof AuthenticatedInasistentesRoute
  '/seguimiento': typeof AuthenticatedSeguimientoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/movil/asistencia': typeof AuthenticatedMovilAsistenciaRoute
  '/movil/calendario': typeof AuthenticatedMovilCalendarioRoute
  '/movil/qr': typeof AuthenticatedMovilQrRoute
  '/movil/semaforo': typeof AuthenticatedMovilSemaforoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/actas': typeof AuthenticatedActasRoute
  '/crear-acta': typeof AuthenticatedCrearActaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evidencias': typeof AuthenticatedEvidenciasRoute
  '/inasistentes': typeof AuthenticatedInasistentesRoute
  '/seguimiento': typeof AuthenticatedSeguimientoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/movil/asistencia': typeof AuthenticatedMovilAsistenciaRoute
  '/movil/calendario': typeof AuthenticatedMovilCalendarioRoute
  '/movil/qr': typeof AuthenticatedMovilQrRoute
  '/movil/semaforo': typeof AuthenticatedMovilSemaforoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/_authenticated/actas': typeof AuthenticatedActasRoute
  '/_authenticated/crear-acta': typeof AuthenticatedCrearActaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evidencias': typeof AuthenticatedEvidenciasRoute
  '/_authenticated/inasistentes': typeof AuthenticatedInasistentesRoute
  '/_authenticated/seguimiento': typeof AuthenticatedSeguimientoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/movil/asistencia': typeof AuthenticatedMovilAsistenciaRoute
  '/_authenticated/movil/calendario': typeof AuthenticatedMovilCalendarioRoute
  '/_authenticated/movil/qr': typeof AuthenticatedMovilQrRoute
  '/_authenticated/movil/semaforo': typeof AuthenticatedMovilSemaforoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/actas'
    | '/crear-acta'
    | '/dashboard'
    | '/evidencias'
    | '/inasistentes'
    | '/seguimiento'
    | '/usuarios'
    | '/movil/asistencia'
    | '/movil/calendario'
    | '/movil/qr'
    | '/movil/semaforo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/actas'
    | '/crear-acta'
    | '/dashboard'
    | '/evidencias'
    | '/inasistentes'
    | '/seguimiento'
    | '/usuarios'
    | '/movil/asistencia'
    | '/movil/calendario'
    | '/movil/qr'
    | '/movil/semaforo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/demo'
    | '/login'
    | '/_authenticated/actas'
    | '/_authenticated/crear-acta'
    | '/_authenticated/dashboard'
    | '/_authenticated/evidencias'
    | '/_authenticated/inasistentes'
    | '/_authenticated/seguimiento'
    | '/_authenticated/usuarios'
    | '/_authenticated/movil/asistencia'
    | '/_authenticated/movil/calendario'
    | '/_authenticated/movil/qr'
    | '/_authenticated/movil/semaforo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seguimiento': {
      id: '/_authenticated/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof AuthenticatedSeguimientoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inasistentes': {
      id: '/_authenticated/inasistentes'
      path: '/inasistentes'
      fullPath: '/inasistentes'
      preLoaderRoute: typeof AuthenticatedInasistentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evidencias': {
      id: '/_authenticated/evidencias'
      path: '/evidencias'
      fullPath: '/evidencias'
      preLoaderRoute: typeof AuthenticatedEvidenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crear-acta': {
      id: '/_authenticated/crear-acta'
      path: '/crear-acta'
      fullPath: '/crear-acta'
      preLoaderRoute: typeof AuthenticatedCrearActaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/actas': {
      id: '/_authenticated/actas'
      path: '/actas'
      fullPath: '/actas'
      preLoaderRoute: typeof AuthenticatedActasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movil/semaforo': {
      id: '/_authenticated/movil/semaforo'
      path: '/movil/semaforo'
      fullPath: '/movil/semaforo'
      preLoaderRoute: typeof AuthenticatedMovilSemaforoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movil/qr': {
      id: '/_authenticated/movil/qr'
      path: '/movil/qr'
      fullPath: '/movil/qr'
      preLoaderRoute: typeof AuthenticatedMovilQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movil/calendario': {
      id: '/_authenticated/movil/calendario'
      path: '/movil/calendario'
      fullPath: '/movil/calendario'
      preLoaderRoute: typeof AuthenticatedMovilCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movil/asistencia': {
      id: '/_authenticated/movil/asistencia'
      path: '/movil/asistencia'
      fullPath: '/movil/asistencia'
      preLoaderRoute: typeof AuthenticatedMovilAsistenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActasRoute: typeof AuthenticatedActasRoute
  AuthenticatedCrearActaRoute: typeof AuthenticatedCrearActaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvidenciasRoute: typeof AuthenticatedEvidenciasRoute
  AuthenticatedInasistentesRoute: typeof AuthenticatedInasistentesRoute
  AuthenticatedSeguimientoRoute: typeof AuthenticatedSeguimientoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedMovilAsistenciaRoute: typeof AuthenticatedMovilAsistenciaRoute
  AuthenticatedMovilCalendarioRoute: typeof AuthenticatedMovilCalendarioRoute
  AuthenticatedMovilQrRoute: typeof AuthenticatedMovilQrRoute
  AuthenticatedMovilSemaforoRoute: typeof AuthenticatedMovilSemaforoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActasRoute: AuthenticatedActasRoute,
  AuthenticatedCrearActaRoute: AuthenticatedCrearActaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvidenciasRoute: AuthenticatedEvidenciasRoute,
  AuthenticatedInasistentesRoute: AuthenticatedInasistentesRoute,
  AuthenticatedSeguimientoRoute: AuthenticatedSeguimientoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedMovilAsistenciaRoute: AuthenticatedMovilAsistenciaRoute,
  AuthenticatedMovilCalendarioRoute: AuthenticatedMovilCalendarioRoute,
  AuthenticatedMovilQrRoute: AuthenticatedMovilQrRoute,
  AuthenticatedMovilSemaforoRoute: AuthenticatedMovilSemaforoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
